### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheVerl** [sebastiandoe5/LatinLookup#1]
When I type in a word that is not a real Latin word, the app just loads forever. We should add a timeout feature, or even better just make sure to check if the word even exists in the Wiktionary database (I'm guessing the app as it is right now just continuously consults the database to see if the word exists?). Another thing that should be added is to set everything to lowercase (apart from proper nouns), so that when I type in 'Vallum' it does not stall forever, and instead goes to 'vallum'.

**Comment by TheVerl** [comment]
I'll just do it myself.

**Comment by sebastiandoe5** [comment]
Thanks @TheVerl for the suggestion, and sorry for not noticing this issue when it was first opened. I have updated the searching algorithm based on your suggestions so that if the word isn't found, it either converts it to lowercase or capitalises it. If the word still isn't found, it now displays an error saying that it couldn't find the word instead of infinitely loading. Thanks again, and I will add your name to the contributors list in the footer of the page for your suggestions.
